pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yusranadepratama/demo-springboot"
        KUBERNETES_NAMESPACE = "default"
        DEPLOYMENT_NAME = "hello-world-deployment"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/yusranad0404/springboot-with-dokcer.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$BUILD_NUMBER .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-credentials-id', variable: 'DOCKER_HUB_PASSWORD')]) {
                    sh 'echo $DOCKER_HUB_PASSWORD | docker login -u yusranadepratama --password-stdin'
                    sh 'docker push $DOCKER_IMAGE:$BUILD_NUMBER'
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    sh "sed -i 's+${DOCKER_IMAGE}:.*+${DOCKER_IMAGE}:${BUILD_NUMBER}+g' SRE/DevOps/deployment.yml"

                    sh '''
                    kubectl apply -f SRE/DevOps/deployment.yml
                    kubectl apply -f SRE/DevOps/service.yml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}
