apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world  # Must match the labels defined in your Deployment
  ports:
    - protocol: TCP
      port: 80  # The port exposed outside the cluster
      targetPort: 8080  # The port the application is listening on inside the pod
  type: LoadBalancer  # You can also use NodePort or ClusterIP depending on your needs